name: rtmp_publisher
description: Controlling the camera on Android and iOS plus rtmp live streaming support. Based off the Camera plugin.
version: 0.3.7
homepage: https://github.com/nhancv/flutter_rtmp_publisher

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  path_provider: null
  video_player: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.11.1

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.app.rtmp_publisher
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: RtmppublisherPlugin
